Nikitin alex
VK-BMSTU-QA/units-autumn-2024 pull request #15
Opened 2024-10-05 10:57 UTC by Olegsandrik

2024-10-05 12:52 UTC, oFem1m commented
И надо добить MainPage

2024-10-05 18:46 UTC, oFem1m commented on backend/src/test_calculator.py
> -from src.calculator import Calculator
случайно ревью не сохранил, это старый коммент

2024-10-05 18:46 UTC, oFem1m commented
аппрув

2024-10-05 19:11 UTC, FunnyRockfish reviewed
Всё хорошо, покрытие полное, но лучше поправить бекенд тестирование

2024-10-05 19:11 UTC, FunnyRockfish commented on backend/src/test_calculator.py
> +        error_message = "unsupported operand type(s) for +: 'int' and 'str'"
А зачем сообщения об ошибках? Мы тестрование делаем. И заранее ожидаем определённое поведение в негативных и позивных кейсах. Поэтому их лучше убрать

2024-10-05 19:11 UTC, FunnyRockfish commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.addition("a", "b"), "ab")
На семинаре сказали, что работаь с буквами не надо - у нас калькулятор для чисел

2024-10-05 19:11 UTC, FunnyRockfish commented on backend/src/test_calculator.py
> +    def test_calc_sub_test10(self):
Этот кейс и подобные ему - лучше тоже убрать, не соответствует ТЗ

2024-10-05 19:22 UTC, Olegsandrik commented on backend/src/test_calculator.py
> +        error_message = "unsupported operand type(s) for +: 'int' and 'str'"
Так это ожидаемое сообщение об ошибки, которое должно совпасть с проверкой. Это ожидаемое поведение

2024-10-05 19:23 UTC, Olegsandrik commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.addition("a", "b"), "ab")
Не помню такого, поэтому использовал тестирование на любых типах данный, как и говорили на семе)
Что надо потыкать все типы данных, которые возможно, чтобы понять поведение на данных

2024-10-13 14:27 UTC, BeeHeather requested changes
Привет! Хорошая работа, есть пара комментариев, посмотри пожалуйста

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
>          self.assertEqual(self.calculator.addition(1, 2), 3)
Го добавим тест на сложение отрицательных чисел

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.addition(True, True), True+True)
Нам необходимо проверять конкретный результат, который выведет калькулятор (вместо True+True подставь конкретное число)

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.multiplication(1, 2), 2)
Добавь умножение отрицательных чисел

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.addition(True, False), True)
Го здесь и далее в аналогичных проверках тоже будем проверять конкретный числовой результат

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
> +    def test_calc_div_test1(self):
Добавь проверку деления, при которой мы получаем целое число, и проверку деления отрицательных чисел

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.ln(1), 0)
Го добавим проверку на нецелое число

2024-10-13 14:27 UTC, BeeHeather commented on backend/src/test_calculator.py
> +        self.assertEqual(self.calculator.sqrt(1), 1)
Го добавим проверку на нецелое число

2024-10-16 10:42 UTC, BeeHeather commented on backend/src/test_calculator.py
> +    def test_calc_add_test1(self):
Давай для тестов дадим более информативные названия, вместо нумерации

2024-10-17 13:52 UTC, BeeHeather approved these changes
Аппрув

2025-02-02 22:40 UTC, closed without merging